# See the documenteer.toml for overrides of the Rubin user guide presets

from documenteer.conf.guide import *  # noqa: F401, F403
nb_execution_mode = 'off'

# The data quality plots are a prebuilt Svelte app, generated by
# https://github.com/lsst-dm/interactive_plots and copied into
# _static/dp2_data_quality (see its PROVENANCE file for the source commit).
html_static_path.append('_static')  # noqa: F405

DATA_QUALITY_PAGE = 'overview/data_quality'


def _add_data_quality_assets(app, pagename, templatename, context, doctree):
    """Attach the plot bundle to its own page.

    Registering on html-page-context keeps both assets off every other page,
    and routing them through Sphinx rather than a hand-written tag in the page
    earns the ?v= digest, so a redeployed bundle is refetched instead of being
    served stale from cache.
    """
    if pagename != DATA_QUALITY_PAGE:
        return
    app.add_css_file('dp2_data_quality/dp2-data-quality.css')
    app.add_js_file('dp2_data_quality/dp2-data-quality.js', type='module')


def setup(app):
    app.connect('html-page-context', _add_data_quality_assets)
